networks:
  quiz:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24

services:
  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      quiz:
        ipv4_address: 10.5.0.6
    restart: always
    ports:
      - "5555:5432"
      - "8181:80"

  redis:
    image: redis:7-alpine
    container_name: redis_quiz_platform
    hostname: redis
    ports:
      - "6379:6379" 
    networks:
      quiz:
        ipv4_address: 10.5.0.7
    restart: always
